#!/usr/bin/env bash
# this runs after `environment.yml` has been installed with `mamba`
set -eux

# prepare
jupyter lab clean --all

# python setup (lab install included)
python -m pip install -e . --no-cache-dir --no-deps

# cleanup
jupyter lab clean
jlpm cache clean

# see what we have
jupyter labextension list
jupyter serverextension list
