#!/usr/bin/env bash
# this runs after `environment.yml` has been installed with `mamba`
set -eux

# prepare
jupyter lab clean --all

# python setup
python -m pip install -e . --no-cache-dir --no-deps

# lab
jupyter labextension list
jupyter lab build --debug --dev-build=False --minimize=False
jupyter labextension list

# cleanup
jupyter lab clean
jlpm cache clean

# see what we have
jupyter labextension list
jupyter serverextension list
