#!/usr/bin/env python3
""" perform a development install of ipyradiant

    On mybinder.org, this will run _after_ the environment has been fully
    created from environment.yml.

    This script should also run locally on Linux/MacOS/Windows:

        python3 binder/postBuild
"""
import subprocess
import sys
from pathlib import Path


ROOT = Path.cwd()
LAB_EXTENSIONS = ROOT / "labextensions.txt"


def _(*args, **kwargs):
    """ Run a command, echoing the args

        fails hard if something goes wrong
    """
    print("\n\t", " ".join(args), "\n")
    return_code = subprocess.call(args, **kwargs)
    if return_code != 0:
        print("\nERROR", return_code, " ".join(args))
        sys.exit(return_code)

# verify the environment is self-consistent before even starting
_(sys.executable, "-m", "pip", "check")

# install the python package
# _(sys.executable, "-m", "pip", "install", "-e", ".")

# verify the environment the extension didn't break anything
_(sys.executable, "-m", "pip", "check")

# install dependencies
_("jlpm", "--prefer-offline", "--ignore-optional")

# initially list installed extensions to determine if there are any surprises
_("jupyter", "labextension", "list")

# install the labextension
_("jupyter", "labextension", "install", "--no-build", "--debug",
    *[
        ext.strip()
        for ext in LAB_EXTENSIONS.read_text().splitlines()
        if ext.strip() and not ext.strip().startswith("#")
    ]
)

# disable extension manager because slow
_("jupyter", "labextension", "disable", "@jupyterlab/extension-manager-extension")

# verify the list of extensions
_("jupyter", "labextension", "list")

# verify the list of extensions
_("jupyter", "lab", "build", "--dev-build=False", "--minimize=True")

# verify the list of extensions one last time
_("jupyter", "labextension", "list")

print("JupyterLab with ipyradiant is ready to run with:\n")
print("\tjupyter lab\n")
