name: ipyradiant-base

channels:
  - https://conda.anaconda.org/conda-forge
  - nodefaults

dependencies:
  - anaconda-project =0.10.2
  - conda =4.11.0
  - doit
  - pip
  - pip:
    - git+https://github.com/jvesely/cloudpickle.git@master
  - python >=3.9,<3.10
  - twine
  - mamba =0.21.0
