name: ipyradiant-base

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - anaconda-project
  - conda
  - doit >=0.36
  - pip
  - pip:
    - git+https://github.com/jvesely/cloudpickle.git@master
  - python >=3.9,<3.10
  - twine
  - mamba
