name: ipyradiant-base

channels:
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/anaconda
  - https://conda.anaconda.org/msys2

dependencies:
  - anaconda-project =0.8.4
  - conda >=4.8,<4.9
  - doit =0.32
  - python >=3.7,<3.8
