name: ipyradiant-base

channels:
  - https://conda.anaconda.org/conda-forge
  - nodefaults

dependencies:
  - anaconda-project =0.10.2
  - conda =4.11.0
  - doit =0.34.1
  - pip
  - python >=3.9,<3.10
  - twine =3.8
  - mamba =0.21.0
