{% set name = "ipyradiant" %}
{% set version = "0.1.0" %}
{% set dist = name ~ "-" ~ version %}
{% set fname = dist ~ ".tar.gz" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - path: ../dist/{{ fname }}
  - path: ../LICENSE

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -c "__import__('tarfile').open('{{ fname }}').extractall()"
    - cd {{ dist }}
    - {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - bokeh
    - datashader
    - holoviews
    - ipycytoscape >=1.0.3
    - ipywidgets
    - networkx
    - pandas
    - python >=3.6
    - qgrid
    - rdflib
    - rdflib-jsonld
    - scikit-image

test:
  requires:
    - pip
  imports:
    - ipyradiant
  commands:
    - python -m pip check

about:
  home: https://github.com/jupyrdf/ipyradiant
  license: BSD-3-Clause
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter Widgets for working with RDF graphs
